services:
  backend:
    image: nobugsme/nbank:with_database_with_fix
    ports:
      - "4111:4111"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nbank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - nbank-network

  frontend:
    image: nobugsme/nbank-ui:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nbank-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nbank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - nbank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d nbank" ]
      interval: 10s
      timeout: 5s
      retries: 5

  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/:/etc/selenoid/:ro
    command: ["-container-network", "nbank-network"]
    depends_on:
      - frontend
    networks:
      - nbank-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
    depends_on:
      - selenoid
    networks:
      - nbank-network

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8085:8085"
    command: [ "--port", "8085", "--verbose" ]

networks:
  nbank-network:
    name: nbank-network

volumes:
  postgres_data:
    driver: local