name: Run tests

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'checkstyle.xml'
      - '.github/workflows/run-tests.yml'
  workflow_dispatch:

jobs:
  setup:
    name: Set up jdk and repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


  setup-and-run-tests:
    name: Set up services
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up services
        run: |
          pwd
          cd infra/docker_compose && pwd
          bash ./restart-docker.sh
          cd ../..
          pwd

      - name: Set permissions
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test -P api -q
        env:
          APIBASEURI: http://localhost:4111
          UIBASEURL: http://frontend

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check

  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [ setup, setup-and-run-tests ]
    if: success()

    strategy:
      max-parallel: 1
      matrix:
        attempt: [1, 2, 3]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit hash
        id: get-commit-hash
        run: |
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "SHORT_HASH=$SHORT_HASH"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Pre-build project
        run: |
          chmod +x mvnw

      - name: Run push script with commit hash
        run: |
          chmod +x push-tests.sh
          echo "Using commit hash: ${{ steps.get-commit-hash.outputs.short_hash }}"
          ./push-tests.sh "${{ steps.get-commit-hash.outputs.short_hash }}"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}